language: d

os:
  - linux
  - osx

d:
  # support 3 versions
  - dmd
  - dmd-2.092.1
  - dmd-2.091.1
  - dmd-2.090.1
  - ldc
  - ldc-1.20.0
  - ldc-1.19.0
  - ldc-1.18.0

script:
  - dub test -b unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

test:
  dub test