language: d

os:
  - linux
  - osx

d:
  # support 3 versions
  - dmd
  - dmd-2.100.2
  - dmd-2.099.1
  - dmd-2.098.1
  - ldc
  - ldc-1.30.0
  - ldc-1.29.0
  - ldc-1.28.0

script:
  - dub test -b unittest-cov

after_success:
 - bash <(curl -s https://codecov.io/bash)

test:
  dub test